- name: ansible create directory worker
  file:
    path: /var/www/worker
    state: directory

- name: Extract worker.tar and upload
  ansible.builtin.unarchive:
    src: worker.tar
    dest: /var/www/worker/
    extra_opts: [--strip-components=1]

- name: Install Java using Ansible
  apt:
    name: openjdk-11-jdk
    state: present

- name: install maven (and other packages if needed)
  become: yes
  apt: pkg=maven state=latest update_cache=yes cache_valid_time=3600

- name: Maven install pom
  command: mvn -f /var/www/worker/pom.xml clean package

- name: Template service
  ansible.builtin.template:
    src: templates/worker.j2
    dest: /etc/systemd/system/worker.service
    mode: '0644'

- name: Start service worker, if not started
  ansible.builtin.service:
    name: worker.service
    state: started