- name: ansible create directory poll
  file:
    path: /var/www/poll
    state: directory

- name: Extract poll.tar and upload
  ansible.builtin.unarchive:
    src: poll.tar
    dest: /var/www/poll/
    extra_opts: [--strip-components=1]

- name: install pip3
  apt: name=python3-pip state=present 

- name: Install specified python requirements
  ignore_errors: true
  pip:
    requirements: /var/www/poll/requirements.txt

- name: Template service
  ansible.builtin.template:
    src: templates/poll.j2
    dest: /etc/systemd/system/poll.service
    mode: '0644'

- name: Start service poll, if not started
  ansible.builtin.service:
    name: poll.service
    state: started